### ISSUE TITLE
“下载”命令失败。

### ISSUE THREAD

**Issue by do-kiss** [ppkantorski/Ultrahand-Overlay#172] opened 2024-08-23 04:57 UTC
The "download" command has completely stopped working. It seems to be related to ultrahand and nx-ovlloader. When I switched back to version 1.0.7 of nx-ovlloader and an older version of ultrahand, the "download" command started working normally again.

**Comment by ppkantorski** [comment] 2024-08-24 06:25
i need more details to understand your current concerns.

What version of nx-ovlloader were you using when you had issues?  What version are you testing (v1.6.9?)?  What version did downloads not have problems, and is it not working in every test case or just certain test cases (i.e. can you trigger it by doing something specific)?

**Comment by do-kiss** [comment] 2024-08-24 07:23
Hello, I conducted more detailed tests. When I use Ultrahand 1.6.8 with nx-ovlloader 1.0.7, the "download" command works fine. However, if I replace the `ovlmenu.ovl` of Ultrahand with version 1.6.9, the "download" command stops working. When I click the download button, a ❌ appears immediately, as if it didn’t even attempt to download. The ❌ appears instantly.

If I use the optimized nx-ovlloader 1.0.8 with Ultrahand 1.6.9, the "download" command still doesn’t work. However, if I switch the `ovlmenu.ovl` of Ultrahand back to version 1.6.8, it works normally again.

So, I’m now certain that the reason the "download" command isn’t working is related only to Ultrahand version 1.6.9. It doesn’t seem to be related to nx-ovlloader.

**Comment by do-kiss** [comment] 2024-08-24 07:33
Currently, this error is triggered 100% of the time for me. As long as I use the `ovlmenu.ovl` from Ultrahand 1.6.9, the "download" command becomes unusable. I tested download links from both GitHub and my own server, and the issue occurs with both. I’m not sure if this is related to "https"? Both GitHub and my server enforce the use of https. I saw another comment mentioning that https might affect the "download" command—this is just my guess. 

Additionally, could "download" and "unzip" support paths with Chinese characters? If my download link or the path inside the archive contains Chinese characters, various errors occur. I have to use paths entirely in English, which isn’t very user-friendly for those of us in a Chinese environment. Thank you very much for your hard work in creating such a useful tool.

**Comment by ppkantorski** [comment] 2024-08-24 08:27
Hmm, perhaps your time might be off.  I forgot, this happened to me once.  I had to sync the time with NTP.  Since there is SSL encryption with downloads the system clock must be synced properly.  Sometimes using android, linux, hekate, or jest overclocking the time can be offset.  Let me know if this helps

**Comment by do-kiss** [comment] 2024-08-24 08:34
I’m certain that my system time is already synchronized. The download error only appears in Ultrahand 1.6.9. I just synchronized the system time again, and the time synchronization plugin works fine, but the Ultrahand download command still doesn't work. It only works properly when I switch back to version 1.6.8.
In short, time synchronization doesn’t solve the issue, but switching back to Ultrahand 1.6.8 does.

**Comment by ppkantorski** [comment] 2024-08-24 08:36
Can you check the `/config/ultrahand/log.txt` file and show me the error it is printing?

**Comment by do-kiss** [comment] 2024-08-24 08:43
Could you please try this link to see if you can access my `log.txt`? This is the complete log.
https://pan.dokiss.cn/d/SwitchLib/log.txt

**Comment by ppkantorski** [comment] 2024-08-24 09:00
I cant access it.  Can you just find the line where it logs the error by any chance?  You can delete the log.txt, then try the command again, then share the log.txt with the errors logged directly here as text.

**Comment by do-kiss** [comment] 2024-08-24 09:05
I deleted the `log.txt`. This is the complete content of the log that was automatically generated after I attempted to download three times.
[2024-08-24 17:02:38] Error opening file: sdmc:/config/ultrahand/downloads/theme.txt.tmp
[2024-08-24 17:02:38] Error opening file: sdmc:/config/ultrahand/downloads/theme.txt.tmp
[2024-08-24 17:02:38] Error opening file: sdmc:/config/ultrahand/downloads/theme.txt.tmp
[2024-08-24 17:02:41] Error opening file: sdmc:/config/ultrahand/downloads/HuanTa.zip.tmp
[2024-08-24 17:02:41] Error opening file: sdmc:/config/ultrahand/downloads/HuanTa.zip.tmp
[2024-08-24 17:02:41] Error opening file: sdmc:/config/ultrahand/downloads/HuanTa.zip.tmp
[2024-08-24 17:02:41] Error opening zip file: sdmc:/switch/.packages/More Menu/Theme Custom/Data/themeslib/HuanTa.zip
[2024-08-24 17:02:44] Error opening file: sdmc:/config/ultrahand/downloads/JiJiaShaoNv.zip.tmp
[2024-08-24 17:02:44] Error opening file: sdmc:/config/ultrahand/downloads/JiJiaShaoNv.zip.tmp
[2024-08-24 17:02:44] Error opening file: sdmc:/config/ultrahand/downloads/JiJiaShaoNv.zip.tmp
[2024-08-24 17:02:44] Error opening zip file: sdmc:/switch/.packages/More Menu/Theme Custom/Data/themeslib/JiJiaShaoNv.zip

**Comment by ppkantorski** [comment] 2024-08-24 09:12
maybe your `/config/ultrahand/downloads/` folder is not present?

**Comment by do-kiss** [comment] 2024-08-24 09:14
Wow! It seems I’ve solved the issue. I just created a `downloads` folder in the `/config/ultrahand/` directory, and now the "download" command is working normally again! It appears that if the `downloads` directory does not exist, the "download" command becomes ineffective. I hope you can fix this.
---
Additionally, I’ve discovered an issue caused by your nx-ovlloader 1.0.8. When I use nx-ovlloader 1.0.8, the DBI plugin encounters many problems, such as a 40% reduction in game installation speed, instability during installation, and frequent interruptions. However, when I switch back to nx-ovlloader 1.0.7, DBI runs very smoothly, installing a 200GB game in one go without interruption and with fast speed.

**Comment by ppkantorski** [comment] 2024-08-24 09:15
1.0.8+ or 1.0.8?

**Comment by do-kiss** [comment] 2024-08-24 09:17
The issue occurs with both 1.0.8 and 1.0.8+, and I spent 6 hours testing the instability of DBI. I confirmed that the problem is caused by nx-ovlloader, and only switching back to nx-ovlloader 1.0.7 ensures stable and fast game installations.

**Comment by do-kiss** [comment] 2024-08-24 09:20
Yes, I obtained 1.0.8 and 1.0.8+ from your GitHub. Currently, besides causing instability during the DBI game installation process, there don’t seem to be any other issues.

**Comment by do-kiss** [comment] 2024-08-24 09:28
Regarding the issue of supporting Chinese characters in the "download" and "unzip" commands, as far as I know, ANSI encoding can display Chinese characters correctly in the command line, while UTF-8 can cause various garbled characters. I’m not sure if this information is helpful.

**Comment by ppkantorski** [comment] 2024-08-24 09:38
I recompiled nx-ovlloader again right now and re-uploaded.  Not sure if this will fix anything though, but you can test it out.  The issue you described sounds very strange to me.  Not sure why that would be happening.  It could have to do with the dependencies, but this is the first I've ever heard of such issue.

**Comment by do-kiss** [comment] 2024-08-24 09:48
Alright, thank you. I have downloaded the 1.0.8 and 1.0.8+ versions you just compiled. I will test them and get back to you with the results, which will take about 4 hours.

**Comment by ppkantorski** [comment] 2024-08-24 09:52
heads up, for the loader+ i forgot to change the version label.  its fixed as of right now (reupload).

**Comment by do-kiss** [comment] 2024-08-24 09:54
Got it.

**Comment by do-kiss** [comment] 2024-08-24 11:26
I tested it, and after using the newly compiled nx-ovlloader 1.0.8 and 1.0.8+, DBI is working normally. The game installation speed and stability are just as good as 1.0.7. Everything is great！

**Comment by ppkantorski** [comment] 2024-08-24 12:42
i did some more investigating.  someone else was able to trigger the same issue on regular nx-ovlloader (1.0.6/1.0.7).  apparently its random, so it is likely a DBI bug.  But im glad it stopped for you, but dont be surprised if it comes back.

**Comment by do-kiss** [comment] 2024-08-24 12:52
It might not be a random issue. In my group chat with around 4000 members, ever since using your older nx-ovlloader 1.0.8, I received a lot of feedback regarding DBI being unusually unstable. I also conducted tests myself and confirmed that the issue originated from nx-ovlloader (including trying different DBI versions, switching languages, and conducting extensive tests). After using your newly compiled 1.0.8 today, my group chat members all reported that DBI is now working normally again. Although I'm not sure what the difference is between the new and old 1.0.8 versions, it has indeed completely resolved the DBI instability issue. Thank you very much!

**Comment by ppkantorski** [comment] 2024-08-24 15:30
I had someone look into it.  They were able to reproduce the bug on WerWolv's nx-ovlloader.  However it is random, it randomly appears then randomly disappears.  Not sure whats going on with DBI tbh, but if it is good for your end then thats good news to me.  Going to close this issue.  If you have other concerns lmk. 🙏🏼

**Closed by ppkantorski** 2024-08-24 15:30 UTC
