### ISSUE TITLE
Navigation in forwarders

### ISSUE THREAD

**Issue by gczark** [ppkantorski/Ultrahand-Overlay#211] opened 2024-10-21 12:12 UTC
A slight modification of script to access OC info, the directory is changed to a hidden one:

```
[*Info]
;mode=forwarder
package_source './.OC Toolkit/info.ini'
```

The problem comes when exiting the `info.ini`
1. exiting via `B` as `controller` input closes the entire ultrahand;
2. exiting via `touch` input, returns to packages list normally.

**Comment by ppkantorski** [comment] 2024-10-22 08:49
I dont get the same issue doing what you are doing. 
<img width="548" alt="Screenshot 2024-10-22 at 1 47 08 AM" src="https://github.com/user-attachments/assets/0ca084ff-0d55-44cd-8a6d-ce6ef2404c11">

You are assuming a structure that looks like this with your use of the forwarder.

```
[*Info 2]
;mode=forwarder
package_source './.OC Toolkit/info.ini'
```

Now with a method like this, it will draw the info properly.  Clicking B exits as normal for me, so i cant reproduce your results.  Not sure if this is what you are trying to do (or why) but be cautious of the `./` which will return the path of the active folder the ini is running in.

**Comment by gczark** [comment] 2024-10-23 01:29
The script is located in `package.ini`

> [*Info]
> ;mode=forwarder
> package_source './.OC Toolkit/info.ini'

The path location of `info.ini`
/switch/.packages/.OC Toolkit/info.ini

Also tried using the absolute path, same result

**Comment by ppkantorski** [comment] 2024-10-23 05:07
> The script is located in `package.ini`
> 
> > [*Info]
> > ;mode=forwarder
> > package_source './.OC Toolkit/info.ini'
> 
> The path location of `info.ini` /switch/.packages/.OC Toolkit/info.ini
> 
> Also tried using the absolute path, same result

if that is your path, you would just use `./info.ini`

**Comment by ppkantorski** [comment] 2024-10-24 01:14
i may have also coded it to not work with hidden package folders, now that i've looked into it more.  when i make the folder hidden, i cant enter the package / it isnt drawn on the menu.  why exactly are you trying to make the folder hidden again?

**Comment by ppkantorski** [comment] 2024-10-27 03:53
Going to be closing this issue since there hasn't been any further details on what you are trying to achieve.  Hopefully your issue is already resolved.  If you have any additional questions, feel free to ask here and I will try to respond.

**Closed by ppkantorski** 2024-10-27 03:53 UTC
